### PR TITLE
Pass key_len to bcrypt(). Fix for issues kelektiv#774, kelektiv#776

### LINKED ISSUE #774: Passwords are stripped after an ASCII NUL character
## What went wrong?
When hashing a password containing an ASCII NUL character, that character acts as the string terminator. Any following characters are ignored.

## What did you expect to happen?
Strings should be handled exactly like in JavaScript, where NUL characters can occur at any position without affecting their length. I realize this is kind of an odd case, but since this is a security-relevant module, it should always behave exactly the way it is supposed to.

## Which version of nodejs and OS?
node v12.13.1 on Fedora 31 x86_64

## If you find a bug, please write a failing test.
```js
const bcrypt = require('bcrypt');
const assert = require('assert');

const actualPasswd = 'Passw\0rd123';
const badPasswd = 'Passw\0 you can literally write anything after the NUL character';

async function test() {
    const hash = await bcrypt.hash(actualPasswd, 12);

    const resultWithActualPasswd = await bcrypt.compare(actualPasswd, hash);
    const resultWithBadPasswd = await bcrypt.compare(badPasswd, hash);

    assert.strictEqual(resultWithActualPasswd, true, 'Should return true with the actual password');
    assert.strictEqual(resultWithBadPasswd, false, 'Should return false with a bad password');
}

test()
    .then(() => console.log('Test passed'))
    .catch(console.error);
```

### LINKED ISSUE #776: Some compatibility issue with emoji
When using 64+ emoji compatibility between bcrypt <> php and bcrypt <> bcryptjs is broken, whereas bcryptjs <> php is fine.
Code to represent the issue.
```
const {spawnSync} = require('child_process');
const bcrypt = require('bcrypt');
const bcryptjs = require('bcryptjs');

let chr = '😃'; // emoji
let len = 64; // 64+
let data = chr.repeat(len);

let bcryptAHash = bcrypt.hashSync(data, bcrypt.genSaltSync(8, 'a'));
let bcryptBHash = bcrypt.hashSync(data, bcrypt.genSaltSync(8, 'b'));
let bcryptjsHash = bcryptjs.hashSync(data, bcryptjs.genSaltSync(8));
let phpHash = spawnSync("php", ["-r", "echo password_hash('"+data+"', PASSWORD_BCRYPT, ['cost' => 8]);"]).stdout.toString();

let bcrypta_php = spawnSync("php", ["-r", "echo password_verify('"+data+"', str_replace('$2a$', '$2y$', '"+bcryptAHash+"')) ? 'true' : 'false';"]).stdout.toString();
let bcryptb_php = spawnSync("php", ["-r", "echo password_verify('"+data+"', str_replace('$2b$', '$2y$', '"+bcryptBHash+"')) ? 'true' : 'false';"]).stdout.toString();
let bcryptjs_php = spawnSync("php", ["-r", "echo password_verify('"+data+"', str_replace('$2a$', '$2y$', '"+bcryptjsHash+"')) ? 'true' : 'false';"]).stdout.toString();
let php_php = spawnSync("php", ["-r", "echo password_verify('"+data+"', '"+phpHash+"') ? 'true' : 'false';"]).stdout.toString();

let bcrypta_bcrypt = bcrypt.compareSync(data, bcryptAHash).toString();
let bcryptb_bcrypt = bcrypt.compareSync(data, bcryptBHash).toString();
let bcryptjs_bcrypt = bcrypt.compareSync(data, bcryptjsHash).toString();
let php_bcrypta = bcrypt.compareSync(data, phpHash.replace("$2y$", "$2a$")).toString();
let php_bcryptb = bcrypt.compareSync(data, phpHash.replace("$2y$", "$2b$")).toString();

let bcrypta_bcryptjs = bcryptjs.compareSync(data, bcryptAHash).toString();
let bcryptjs_bcryptjs = bcryptjs.compareSync(data, bcryptjsHash).toString();
let php_bcryptjs = bcryptjs.compareSync(data, phpHash.replace("$2y$", "$2a$")).toString();

console.log("hash\\module php   bcryptjs bcrypt-a bcrypt-b");
console.log("php        ", php_php.padEnd(5, " "), php_bcryptjs.padEnd(8, " "), php_bcrypta.padEnd(8, " "), php_bcryptb.padEnd(8, " "));
console.log("bcryptjs   ", bcryptjs_php.padEnd(5, " "), bcryptjs_bcryptjs.padEnd(8, " "), bcryptjs_bcrypt.padEnd(8, " "), "".padEnd(8, " "));
console.log("bcrypt-a   ", bcrypta_php.padEnd(5, " "), bcrypta_bcryptjs.padEnd(8, " "), bcrypta_bcrypt.padEnd(8, " "), "".padEnd(8, " "));
console.log("bcrypt-b   ", bcryptb_php.padEnd(5, " "), "".padEnd(8, " "), "".padEnd(8, " "), bcryptb_bcrypt.padEnd(8, " "));
```
The output:
```
hash\module php   bcryptjs bcrypt-a bcrypt-b
php         true  true     false    false   
bcryptjs    true  true     false            
bcrypt-a    false false    true             
bcrypt-b    false                   true    
```
Fedora 31 x86_64, bcrypt 3.0.7, node v12.13.1

### PR DESCRIPTION
**Pull request by techhead**
Fixes #774 #776 

Bcrypt already includes the final NUL termination character when calculating the hash. I believe that also Including those caught in the middle is a reasonable default that will help to prevent a possible class of errors. And it's a simple fix.

This patch also fixes #776, though I previously released a stand-alone patch for it. This one is preferred (by me).

### CODE REVIEW

**Comment by agathver** [comment]
The current bcrypt implementations are fragmented. Some accept nulls and some dont. Given we use OpenBSD bcrypt as the source implementation, and UTF-8 as the  canonical character encoding (which wont contain nulls) this change is controversial, OpenBSD bcrypt doesn't accept nulls in password chars.

**Comment by techhead** [comment]
The NUL character is valid in UTF-8. That's actually kind of part of the problem. This is a javascript library, and the string inputs are coming from javascript strings. If this was a C library, the controversy would be bigger, I imagine. But many (most?) javascript programmers know nothing about NUL-terminated strings.

I think that the expected behavior should be the default behavior as a general rule. It's safer. The programmer who uses this library is generally going to expect that the full input provided is going to be hashed, at least up to the well-documented 72-byte limitation.

But of course, in real-world usage, passwords are not going to contain NUL characters unless someone made a mistake or the password has been pre-processed or pre-hashed in some way. This is the use case that I'm interested in.

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pre-hashing-passwords

As you can see from the OWASP recommendation, implementations that do not hash NULs have been the unexpected cause of unsafe passwords in some cases. 

> As such, the preferred option should generally be to limit the maximum password length. Pre-hashing of passwords should only be performed where there is a specific requirement to do so, and appropriate steps have been taking to mitigate the issues discussed above.

Well, I have a "specific requirement." I'm a big proponent of pass-phrases over passwords. And a 72-byte limitation really works against that.

Pre-hashing is a pretty common means of overcoming the limitation. Dropbox does it. (Or did it, at least. https://dropbox.tech/security/how-dropbox-securely-stores-your-passwords) The easier a library makes to do it safely, the better IMO.

I already have a backwards-compatible branch of this lib that takes either a string or Buffer as an input to further help to do this easily and properly. I'd love to have it merged eventually so I don't have to maintain a separate fork. This is a step towards that.

Anyway, that's my goal, use case, and argument. Thank you for your consideration.

**Comment by agathver** [comment]
> The NUL character is valid in UTF-8. That's actually kind of part of the problem. 

Only as NUL byte. UTF-8 is designed in such a way to avoid NUL anywhere resulting from combination of any multi-byte character.

> This is a javascript library, and the string inputs are coming from javascript strings. If this was a C library, the controversy would be bigger, I imagine. But many (most?) javascript programmers know nothing about NUL-terminated strings.

This I will agree with.

> I already have a backwards-compatible branch of this lib that takes either a string or Buffer as an input to further help to do this easily and properly. I'd love to have it merged eventually so I don't have to maintain a separate fork. This is a step towards that.

I would actually like that. I have been working on a Buffer input for bcrypt for some time now but it's nowhere complete.

Anyway, that's my goal, use case, and argument. Thank you for your consideration.

**Comment by agathver** [comment]
@techhead Can you rebase this off master?

**Comment by techhead** [comment]
> @techhead Can you rebase this off master?

Looks like you already got it done and merged. Thanks for this! I'll send a pull request for using Buffers when I have a version that I feel is ready.

**Pull request merged**
