### PR TITLE
preserve stack traces on async error callbacks

### PR DESCRIPTION
**Pull request by tonylukasavage**
This issue solves the problem detailed in #538 while preserving the true async callbacks merged in #264.

### CODE REVIEW

**Comment by agathver** [comment]
Code LGTM, but it breaks windows x86 targets ? I do not see a reason why. And some builds have run for hours and then they have timed out.

**Comment by tonylukasavage** [comment]
Is this possibly an appveyor issue? Could someone with permissions re-run the build? There's not much to the code change, and certainly nothing platform specific or that would make the build run for an hour.

**Comment by tonylukasavage** [comment]
Well here's the problem, it is appveyor at the moment:

appveyor status

**Comment by agathver** [comment]
@tonylukasavage could you make a push to trigger the CI build ?

**Comment by agathver** [comment]
@tonylukasavage AppVeyor is good now.  If you could squash the last two testing commits and make a push, we would be able to see how the tests fare in appveyor

**Comment by tonylukasavage** [comment]
Looks good now. Ready to merge? If so, when can a version bump and npm release be expected.

**Comment by agathver** [comment]
I'm planning for 2.0 with support for $2b$ hashes and some other fixes somewhere in this month.

**Comment by tonylukasavage** [comment]
is this good to merge? Is there anything else needed? Would really like to get this resolved officially.

**Pull request merged**
