### PR TITLE
Fixing github URL. Related to kelektiv/node.bcrypt.js#486

### PR DESCRIPTION
**Pull request by michelgokan**
It seems many people had this issue.

### CODE REVIEW

**Comment by AChusuei** [comment]
Merge it, merge it!

**Comment by blessingmobile** [comment]
Hi , when is this fix going to be made available?

**Comment by michelgokan** [comment]
@defunctzombie @ncb000gt @goatandsheep I think this is an urgent fix. Need to get merged ASAP.

**Comment by Agathver** [comment]
@michelgokan This change does not solve the issue. It *changes the link of the binary to the source tarball* which is not what is intended. `node-pre-gyp` downloads precompiled binaries which needed to be manually uploaded. It has not been done for the v1.0.x releases

**Comment by michelgokan** [comment]
@Agathver I did this change in my local installation and it completely fixed my problem. People who had the issue also reported this fixed their 404 issue with wrong URL.

**Comment by Agathver** [comment]
It's a complete different URL. I tried `npm install michelgokan/node.bcrypt.js#master`
*It did not fallback to compiling because it found something to download*. However no `bcrypt-lib.node` file was found inside `node_modules/bcrypt/lib/binding`

You can verify this, by requiring `bcrypt` in node.js. It throws the following error
````
/tmp/bcrypt.js.test $ npm install michelgokan/node.bcrypt.js#master

> bcrypt@1.0.2 install /tmp/bcrypt.js.test/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/tmp/bcrypt.js.test/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
/tmp/bcrypt.js.test
└─┬ bcrypt@1.0.2  (git://github.com/michelgokan/node.bcrypt.js.git#543d815b98dc6d977df6ec7e14ccb9e887190fb1)
  ├── bindings@1.2.1 
  ├── nan@2.5.0 
  └─┬ node-pre-gyp@0.6.32 
.
.
.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/bcrypt.js.test/package.json'
npm WARN bcrypt.js.test No description
npm WARN bcrypt.js.test No repository field.
npm WARN bcrypt.js.test No README data
npm WARN bcrypt.js.test No license field.
 /tmp/bcrypt.js.test $ node
> require('har-validator');
{ [Function]
  cache: [Function],
  cacheEntry: [Function],
  content: [Function],
  cookie: [Function],
  creator: [Function],
  entry: [Function],
  har: [Function],
  log: [Function],
  page: [Function],
  pageTimings: [Function],
  postData: [Function],
  record: [Function],
  request: [Function],
  response: [Function],
  timings: [Function] }
> require('bcrypt');
Error: Cannot find module '/tmp/bcrypt.js.test/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/bcrypt.js.test/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
> 
````

**Comment by michelgokan** [comment]
@Agathver This is my output after this change:

```
michelgokan@Michel-Gokans-MacBook-Pro:~/Documents/MeteorBuilds/bundle/programs/server$sudo meteor npm install --save ~/Downloads/node.bcrypt.js-1.0.2.tar.gz 
Password:

> bcrypt@1.0.2 install /Users/michelgokan/Documents/MeteorBuilds/bundle/programs/server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/Users/michelgokan/Documents/MeteorBuilds/bundle/programs/server/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
wrote npm-shrinkwrap.json
meteor-dev-bundle@0.0.0 /Users/michelgokan/Documents/MeteorBuilds/bundle/programs/server
└── bcrypt@1.0.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

```

Before this change this was my output with 404 error with the exact same command :

```
michelkogan@Michel-Kogans-MacBook-Pro:~/Documents/MeteorBuilds/bundle/programs/server$sudo meteor npm install --save bcrypt

> bcrypt@1.0.2 install /Users/michelkogan/Documents/MeteorBuilds/bundle/programs/server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.3 (node-v46 ABI) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
  COPY /Users/michelkogan/Documents/MeteorBuilds/bundle/programs/server/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError missing: fibers@1.0.15, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: meteor-promise@0.8.0, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: node-gyp@3.4.0, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: node-pre-gyp@0.6.29, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: promise@7.1.1, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: semver@4.1.0, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: underscore@1.5.2, required by meteor-dev-bundle@0.0.0
npm WARN saveError missing: source-map-support@https://github.com/meteor/node-source-map-support/tarball/1912478769d76e5df4c365e147f25896aee6375e, required by meteor-dev-bundle@0.0.0
meteor-dev-bundle@0.0.0 /Users/michelkogan/Documents/MeteorBuilds/bundle/programs/server
└── bcrypt@1.0.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
```

So, apparently I didn't get error. However, there is a possibility that you are correct, I'm not 100% sure. If so, then what's the correct URL for the remote path you are mentioning ?

**Comment by Agathver** [comment]
The correct path is what was already there. @ncb000gt used to manually compile and upload them in the repository earlier,  till v0.8.7. However, for v1.0.x series it was not done. 
I started #470 to automate the upload process by sending files from travis.

**Comment by michelgokan** [comment]
@Agathver I see! Thank you.
So, is there any way to manually upload it for the time being and from the next version work on automating this process ? Because its an important bug and at least 5 issues are related to this.

**Comment by michelgokan** [comment]
@Agathver BTW, I could find `node_modules/bcrypt/lib/binding/bcrypt_lib.node` after building my project with my proposed change.

**Comment by Agathver** [comment]
@michelgokan The contributors to the project need to upload the binaries manually. Travis built packages for v1.0.2 are [availabe](https://github.com/Agathver/node.bcrypt.js/releases) (all versions are just v1.0.2) at my fork. @defunctzombie @goatandsheep please see if you can upload them.

The `bcrypt_lib.node` file may be a remnant of the original install which fell back to source compilation. cd into an empty directory and `npm install michelgokan/node.bcrypt.js#master` I couldn't get the library in my system

**Comment by defunctzombie** [comment]
Which path should be correct here? Is it correct to leave it as it is or does the path need to be adjusted to what this PR suggests so that the fallback actually works correctly? Is the fallback working correctly even if the path is wrong? There is a lot of back and forth on various issues on this project all hovering around what seems to be the same fundamental issue around the use of `node-gyp-pre`.

**Comment by Agathver** [comment]
Fallback to compile doesn't work if node-pre-gyp finds something to download in the binary path. It doesn't check whether the download actually contains a compiled binary. It just assumes that the downloaded file contains the binary, and says remote fetching was successful. This gives rise to confusion as `npm install` looks like it is a success.

**Comment by defunctzombie** [comment]
Closing this based on the last comment indicating that this is not the desired solution to the issue.

**Comment by michelgokan** [comment]
@defunctzombie  Can you at least upload the pre-built binary files manually? so that we won't get any error during installation ?

**Comment by defunctzombie** [comment]
I uploaded the windows binaries. Have no been able to extract binaries from travisci manually.

**Comment by michelgokan** [comment]
@defunctzombie  Thanks (Y) Can you also please upload Mac & Linux binaries if possible?

**Comment by cikasfm** [comment]
@defunctzombie too bad this causes to fail on `heroku` - can you please upload binaries for `linux` & `os x`? or do you need any help with that?

thanks!

**Comment by cikasfm** [comment]
Full error:


```
       node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v51-linux-x64.tar.gz
       node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@7.7.0 (node-v51 ABI) (falling back to source compile with node-gyp)
       make: Entering directory `/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/build'
       CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
       CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
       CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
       In file included from ../../nan/nan.h:47:0,
       from ../src/bcrypt_node.cc:1:
       /app/.node-gyp/7.7.0/include/node/node.h:44:33: fatal error: tracing/trace_event.h: No such file or directory
       #include "tracing/trace_event.h"
       ^
       compilation terminated.
       make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
       make: Leaving directory `/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
       gyp ERR! System Linux 3.13.0-105-generic
       gyp ERR! command "/tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/bin/node" "/tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/lib/binding"
       gyp ERR! cwd /tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt
       gyp ERR! node -v v7.7.0
       gyp ERR! node-gyp -v v3.5.0
       gyp ERR! not ok
       node-pre-gyp ERR! build error
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/bin/node /tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/lib/binding' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
       node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
       node-pre-gyp E
100  5011    0  5011    0     0    184      0 --:--:--  0:00:27 --:--:--   868
100  5080    0  5080    0     0    182      0 --:--:--  0:00:27 --:--:--   834RR! System Linux 3.13.0-105-generic
       node-pre-gyp ERR! command "/tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/bin/node" "/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
       node-pre-gyp ERR! cwd /tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt
       node-pre-gyp ERR! node -v v7.7.0
       node-pre-gyp ERR! node-pre-gyp -v v0.6.32
       node-pre-gyp ERR! not ok
       Failed to execute '/tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/bin/node /tmp/build_155a86b37db465a30f4995cf21c75379/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/tmp/build_155a86b37db465a30f4995cf21c75379/node_modules/bcrypt/lib/binding' (1)
```

**Comment by Agathver** [comment]
@defunctzombie, you can get binaries for linux and osx generated from travis at my fork. In order to reproduce, you can pull my changes into another fork, and push a tag (something like v9999.999.99 keeping version at v1.0.2 in package.json. New binaries would be added to v1.0.2 release. You can download them and add them here.

**Comment by wandonye** [comment]
Still getting this error.

**Comment by alvinyen** [comment]
@wandonye me too..

**Comment by xxxtonixxx** [comment]
I have the same problem 😢

**Comment by FinnFrotscher** [comment]
+1
zodern/meteor-up/issues/683

**Comment by agathver** [comment]
@FinnFrotscher We fixed the issue, you shouldn't be getting this issue

**Comment by gongfan99** [comment]
I am trying to deploy to Elastic Beanstalk.

The dependency in package.json is:

```
  "dependencies": {
    "bcrypt": "1.0.3",
    "express": "4.x"
  }
```

and then got this error:

```
Application update failed at 2017-12-02T15:43:24Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed.+ /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install> bcrypt@1.0.3 install /tmp/deployment/application/node_modules/bcrypt> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@8.8.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/bcrypt/build'
gyp ERR! System Linux 4.9.58-18.55.amzn1.x86_64
gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/bin/node" 
```

But I find that the following link is actually valid. If you enter it into browser address, it can be downloaded. It is strange.
https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v57-linux-x64.tar.gz

**Comment by gongfan99** [comment]
The solution is to add the file .npmrc to the application with the content:

```
# Force npm to run node-gyp also as root, preventing permission denied errors in AWS with npm@5
unsafe-perm=true
```
https://stackoverflow.com/questions/46001516/beanstalk-node-js-deployment-node-gyp-fails-due-to-permission-denied/46001517#46001517

**Pull request closed without merging**
