### PR TITLE
Execute tests on Node.js 11

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
@agathver Typically appveyor is really slow at adding new images, but let's see if they already have one!

**Comment by kibertoad** [comment]
@agathver yup, not on appveyor yet

**Comment by agathver** [comment]
Don't they use nvm like Travis?

**Comment by kibertoad** [comment]
@agathver No, I think they have their own docker images, similarly how circleci does it, while Travis just uses vanilla ones.

**Comment by kibertoad** [comment]
@agathver So is the plan now to wait till appveyor has correct image?

**Comment by agathver** [comment]
Let's give another try, can you push and trigger a build? The builds are usually available in a few days.

**Comment by kibertoad** [comment]
@agathver reopened pr, that triggers build already

**Comment by kibertoad** [comment]
@agathver So they still don't support it :)

**Comment by kibertoad** [comment]
@agathver Should it be removed from appveyor for now?

**Comment by kibertoad** [comment]
woohoo! it passed!

**Pull request merged**
