### PR TITLE
Update @mapbox/node-pre-gyp to 1.0.6

### PR DESCRIPTION
**Pull request by hensansi**
https://github.blog/2021-09-08-github-security-update-vulnerabilities-tar-npmcli-arborist/

### CODE REVIEW

**Comment by hensansi** [comment]
Hey, I created this PR and I hope I followed all the guidelines. I only updated the `@mapbox/node-pre-gyp` dependency and run `npm i --package-lock-only`

**Comment by hensansi** [comment]
More information can be found here https://snyk.io/vuln/npm:tar@6.1.0

**Comment by hensansi** [comment]
Actually my mistake I just noticed that I probably just need to update my yarn.lock,
https://snyk.io/test/npm/@mapbox/node-pre-gyp/1.0.2?tab=dependencies

**Comment by jeremyVignelles** [comment]
This is probably still needed because when I run `npm install bcrypt`, it still picks `@mapbox/node-pre-gyp@1.0.0` by default.

Could you reopen this ?

**Pull request closed without merging**
