### PR TITLE
Node8

### PR DESCRIPTION
**Pull request by Nainterceptor**
Hello,

Bcrypt need a little update to compile on nodeJS 8.
Upgrading nan seems to do the job !

Regards,
Gaël

### CODE REVIEW

**Comment by larsdecker** [comment]
Please merge it.

**Comment by schaki** [comment]
Is there a reason this hasn't been merged yet? It looks like the AppVeyor build is only failing on older version of Node.

**Comment by Agathver** [comment]
@defunctzombie ?

**Comment by jgeurts** [comment]
@defunctzombie What needs to happen to get this merged? I'm happy to assist!

**Comment by avegao** [comment]
Please merge it.

**Comment by defunctzombie** [comment]
Please remove package-lock.json.

**Comment by contra** [comment]
Why not use semver on the nan dep so this isn't needed every node release?

**Comment by fcanela** [comment]
Any update in the status? I suppose this is not being merged due it not working on older versions of node

**Comment by fcanela** [comment]
@defunctzombie, I have replicated the changes from @Nainterceptor in #520. I understand two days is still a reasonable react time and in no way I want to take credit or deny his/her contribution. My team needs this patch to be applied (whatever the version). Is anything else I can do to speed up the process?

**Comment by fcanela** [comment]
@defunctzombie any progress in the resolution? is something else needed?

**Comment by defunctzombie** [comment]
Why is the appveyor build failing?

**Comment by Agathver** [comment]
@defunctzombie NPM no longer supports those versions < 4. There is a line in appveyor.yml that installs latest npm.

**Comment by fcanela** [comment]
```
C:\Program Files\nodejs>cd C:\Program Files\nodejs\npm.cmd\..   && npm install npm@latest 
npmnpm WARN npm npm does not support Node.js v0.10.48
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! Unexpected token >
```

**Comment by defunctzombie** [comment]
Bah ok. Well, the option is to install the correct version of npm for the release or to drop support for those old versions. I am relatively ok with dropping support since those versions are very old at this point.

**Comment by fcanela** [comment]
Thanks both, @defunctzombie  and @Nainterceptor . Im closing my PR and hoping the decision of what to do comes soon.

**Comment by fcanela** [comment]
Hello. Sorry for the insistence. This is still an issue for my team. There is something we could do to get it solved or push it further? Any ETA? I know you are probably volunteering and giving your time to the community, so sorry if I sound pushy.

**Comment by yelled3** [comment]
I'm using node 8.1.2

```
The module '[ROOT]/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). Error: The module '[ROOT]/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([ROOT]/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by yelled3** [comment]
@defunctzombie, @Nainterceptor  so lets remove for the failing versions:
```
Environment: nodejs_version=0.10, platform=x64

Environment: nodejs_version=0.10, platform=x86

Environment: nodejs_version=0.12, platform=x64

Environment: nodejs_version=0.12, platform=x86
```

**Comment by fcanela** [comment]
Hello. Sorry for the insistence. Can we do something to make this PR advance?

**Comment by tmayr** [comment]
I'm also waiting on this.

Opened a pull request on HungryUp fork to remove those versions, maybe that'll be a bit faster?

**Comment by Agathver** [comment]
The maintainers are just busy ATM, please have patience

**Comment by contra** [comment]
If the maintainer needs help with this module, feel free to add me as a maintainer for stuff like this.

**Comment by Agathver** [comment]
@Nainterceptor 
Could you add support for appveyor as well ? Here is the patch you need to apply
```
diff --git a/appveyor.yml b/appveyor.yml
index 4dfa345..270ed91 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -24,20 +24,23 @@ environment:
     platform: x64
   - nodejs_version: "7"
     platform: x86
+  - nodejs_version: "8"
+    platform: x64
+  - nodejs_version: "8"
+    platform: x86
 
 install:
   - where npm
   - where node
   - ps: Install-Product node $env:nodejs_version $env:platform
-  - for /f "delims=" %%a in ('where npm') do cd %%a\.. && npm install npm@latest
-  - for /f "delims=" %%a in ('where npm') do cd %%a\.. && npm install node-pre-gyp@latest
+  - 'if %nodejs_version% lss 4 npm install -g npm@2'
+  - 'if %nodejs_version% geq 4 npm install -g npm@5'
   - 'if "%nodejs_version%_%platform%" == "4_x86" (npm config set -g cafile=package.json && npm config set -g strict-ssl=false)'
 
 build: off
 
 artifacts:
-  - path: 'build/stage/**/bcrypt*.tar.gz'
-  - path: package.json
+  - path: 'build/stage/**/bcrypt*.tar.gz'  
 
 test_script:
   - node --version
@@ -45,4 +48,4 @@ test_script:
   - npm test
 
 after_test:
-  - node-pre-gyp package
+  - .\node_modules\.bin\node-pre-gyp package
```

**Comment by Agathver** [comment]
Hi, I added your changes into #527 along with other changes.

**Comment by Nainterceptor** [comment]
Thanks @Agathver, I close this PR so ;)
(Sorry I was off the last week)

**Comment by marcoapferegrino** [comment]
Is the update available for node 8.9.1 ? I remove my .lock file and I update and rebuild but it Still not working.

**Comment by agathver** [comment]
It appears you compiled your module for node6. Do a `npm rebuild bcrypt`

**Comment by marcoapferegrino** [comment]
Yes, but I rebuild with node 8.9 and the error still beign the same

**Pull request closed without merging**
