### PR TITLE
Builds changes

### PR DESCRIPTION
**Pull request by antwal**
Check the builds errors on Travis for OSX and then update the badges links in README after merge

### CODE REVIEW

**Comment by agathver** [comment]
Please be clear on what issue or problem this PR tries to address.

**Comment by antwal** [comment]
@agathver Now Travis is build in progress, please check here OSX error build [Build Completed](https://travis-ci.org/antwal/node.bcrypt.js)

**Comment by agathver** [comment]
@antwal Correct if I am wrong, for I have never used OSX. Those errors look like environment errors to me. (missing libraries and stuff) Specifying what error you are trying to solve/detect in the PR description will help me to understand the nature of the PR more.

Support for NodeJS <= 4 will be removed in the next major version. 

OSX machines in Travis CI are scarce, so builds will run for hours if not days. (Ours currently run for 3 hours). Since there can be a single Travis build going on per project, the CI for all other PRs and branches will be off limits until this finishes.

_Our main use of OSX build matrix is to generate pre-compiled modules. If the code compiles and the tests pass we simply auto-upload it._

I am not in the favour of adding so many jobs per CI build.

**Comment by antwal** [comment]
I understand the problem and I saw that it is very slow to test. In this case, you may only include the latest versions of OSX in the matrix and use nodes js 6.x LTS and 8.x Current.

**Pull request closed without merging**
