### PR TITLE
Backport updates from the NAN version to N-API

### PR DESCRIPTION
**Pull request by NickNaso**
Hi everyone,
with this PR I ported the updates introduced in the NAN version of the add-on to the N-API version.
Furthermore I added the support for **node-pre-gyp** as requested here: **[https://github.com/kelektiv/node.bcrypt.js/issues/513](https://github.com/kelektiv/node.bcrypt.js/issues/513)**

This first effort on porting the add-on to N-API has the purpose to reduce the maintenance cost for developers as discussed here: **[https://github.com/kelektiv/node.bcrypt.js/issues/513](https://github.com/kelektiv/node.bcrypt.js/issues/513)**

**bcrypt**  is one of the most important native add-on and it is tracked by [citgm](https://github.com/nodejs/citgm), but in this issue seems that  it will not work well in the future version of Node.js (v12) See: **[https://github.com/nodejs/node/issues/25060](https://github.com/nodejs/node/issues/25060)**

N-API could help to manage this kind of issues. In general using N-API maintainers do not take care of the changes that happens in **V8** or **node**.

Please consider to review this PR and collaborate together to release this new version.

### CODE REVIEW

**Comment by agathver** [comment]
We need to rework this first. This shows some merge conflicts.

**Comment by NickNaso** [comment]
What do you suggest to proceed?

**Comment by NickNaso** [comment]
Hi @agathver,
I provided to solve the conflicts now I have only problem on Node.js v7 where we never backported the actual version of N-API (v3). My work will proceed on trying to solve this problem.

**Comment by agathver** [comment]
We can skip Node 7. It's EOL

**Pull request merged**
